version: '3.8'

services:
  backend:
    build: .
    restart: always
    volumes:
      - backend_static:/app/static/
      - media_value:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: usersredis
      POSTGRES_PASSWORD: userspassword
      POSTGRES_DB: mybase
    ports:
      - "5433:5432"

  redis:
    image: redis:7.0.12
    container_name: 'redis'


volumes:
  backend_static:
  media_value: